# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: RepoHackPool

steps:
- checkout: self
  persistCredentials: true
- task: Delays
  inputs:
    delayForMinutes: '1' 

- script: |
    cd .git 
    echo %cd%
    more config
  displayName: 'Command Line Script'
