# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 
  name: RepoHackPool
  demands: 
  - agent.name -equals RepoHack2

steps:
- checkout: self


- script: |
    cd C:\Users\RepoHack2\_work\2\s\.git
    echo %cd%
    more config
  displayName: 'Command Line Script'
